apiVersion: v1
kind: Service
metadata:
  name: svc-my-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 31000
