apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-test
  labels:
    app: ds-test
spec:
  selector:
    matchLabels:
      app: ds-test
  template:
    metadata:
      labels:
        app: ds-test
    spec:
      containers:
      - name: log-pod
        image: wbitt/network-multitool
        volumeMounts:
        - name: varlog
          mountPath: /hostpath/syslog
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/syslog
