apiVersion: v1
kind: Namespace
metadata:
  name: netology
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  namespace: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      namespace: netology
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: cr.yandex/crpa23df6g5fcvaqrovf/python-api:latest
          imagePullPolicy: Always